### ISSUE TITLE
parenthesis

### ISSUE THREAD

**Issue by pyramation** [constructive-io/pgsql-parser#20]
This is the original

```sql
INSERT INTO customers (name, email) VALUES ('Microsoft', 'hotline@microsoft.com') ON CONFLICT (name) DO UPDATE SET
email = EXCLUDED.email || ';' || customers.email, level = customers.level + 1, other = EXCLUDED.other;
```

After adding parens in `A_EXPR kind=0`, for nested `A_EXPR`'s:

```sql
INSERT INTO customers (name, email) VALUES ('Microsoft', 'hotline@microsoft.com') ON CONFLICT (name) DO UPDATE SET
email = (EXCLUDED.email || ';') || customers.email, level = customers.level + 1, other = EXCLUDED.other;
```

However, if the A_EXPR uses context, and the A_EXPR is the same operation, potentially we can get rid of parenthesis!

It's just like when you have `A OR B OR C`, since they all use the same OP, it doesn't matter how you parens it... only matters when it changes.

So potentially we can make cleaner parens with context.

**Comment by beeing** [comment]
Hi @pyramation, removing brackets / parenthesis is dangerous unless it is able to match the original query.

I just discovered a bug in the deparser.

`SELECT (field=1 OR field=2) IS TRUE` after deparsed `SELECT field=1 OR field=2 IS TRUE`

The brackets are important to ensure the `IS TRUE` is for OR expression not just the `field=2` part.

**Comment by pyramation** [comment]
Thank you @beeing! I will take a look at this :)

**Comment by pyramation** [comment]
should be fixed now @beeing, thank you for the examples! I've included them in the tests

```
 - pgsql-deparser@13.1.7
 - pgsql-parser@13.1.7
 ```

**Comment by beeing** [comment]
Thanks for the fix @pyramation
