### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by delaneyj** [constructive-io/pgsql-parser#22]
I didn't see any available from @types/pgsql-parser nor in the source.  Does anyone have definitions available?

**Comment by pyramation** [comment]
There are only two functions that matter `deparse` and `parse`

happy to take a PR for a types file :)

**Comment by delaneyj** [comment]
Yeah, it was the result of that recursive `parse` call I was hoping for. :)  I'm going to be using in typescript and have a shim in place so I'll let you know as I find out more.

**Comment by TobyMellor** [comment]
This would be great! +1

**Comment by dforsber** [comment]
Yes, think we need TS types for the AST +1

**Comment by pyramation** [comment]
> This would be great! +1

> Yes, think we need TS types for the AST +1

I made a gist here of the types for all asts. It's JSON, but it's literally all the ASTs... maybe it's possible somebody could parse this into a types file?

https://gist.github.com/pyramation/fb78fb4dded464ba8ea9385f6055df85

I'm not a typescript guru, so if anyone would like to take a stab at this, I'm all for it including a types.d file or whatever is needed

**Comment by pyramation** [comment]
> Yeah, it was the result of that recursive `parse` call I was hoping for. :) I'm going to be using in typescript and have a shim in place so I'll let you know as I find out more.

@delaneyj did you get a shim by chance for `parse`?

**Comment by dforsber** [comment]
I also found this one: https://github.com/oguimbal/pgsql-ast-parser
Which already has types and deparsing too. Started roughly at the same time as this repo was created/forked.

Do you know if there are any differences that matter between these two?

**Comment by pyramation** [comment]
> I also found this one: https://github.com/oguimbal/pgsql-ast-parser
> Which already has types and deparsing too. Started roughly at the same time as this repo was created/forked.
> 
> Do you know if there are any differences that matter between these two?

From the title of the repo they say: "covering the most common syntaxes of pgsql", and seems they have their own lexer/parser: https://github.com/oguimbal/pgsql-ast-parser/blob/master/src/lexer.ts

That means that it's a home-brew parser, not a real parser like this repository. This repository literally builds on the C code that comes from Postgres itself.

Our parser covers *all* postgres syntax. In fact, you can check out our suite of 242 sql files to cover 1000s of tests cases here: https://github.com/pyramation/pgsql-parser/tree/master/__fixtures__

Now, while I imagine that our repo will be superior in it's ability to parse and deparse all postgres syntax... likely for your use-case you may not need that. Additionally, it looks that their repo will be much more portable... potentially runnable in a browser. So if you just casually use postgres and/or only need a subset of the dialect, then potentially worth considering the typescript repo.

**Comment by pyramation** [comment]
I'm keeping this issue on topic in regards to other parsing libraries out there.

**Comment by pyramation** [comment]
re-opening

**Comment by beeing** [comment]
Hi @pyramation noticed the JSON is missing some from https://github.com/postgres/postgres/blob/REL_13_STABLE/src/include/nodes/parsenodes.h

Are those ok to include as well?

**Comment by beeing** [comment]
Was converting your JSON earlier but still WIP. You can check out https://gist.github.com/beeing/9f7ca576bb344cc772b18c825ec3eab6

**Comment by pyramation** [comment]
oh wow, this is pretty cool @beeing ! 👏🏻👏🏻👏🏻

thanks for putting this together. 

> Hi @pyramation noticed the JSON is missing some from https://github.com/postgres/postgres/blob/REL_13_STABLE/src/include/nodes/parsenodes.h
> 
> Are those ok to include as well?

Include everything that you'd need! I think some of the structures in the parsenodes.h are internal, and not necessarily used. If you notice required objects that are missing, please notify which ones exactly! Would be helpful, thanks again!

**Comment by beeing** [comment]
So far there's some enums that I'm using usually for the kind fields as the new parser return CONSTANT strings rather than integer as per pg-query-native.

Other than that, I like your deparser which return query that is cleaner without too many `"` and brackets.

**Comment by wesselvdv** [comment]
Here are the typescript definitions for libpg-query-node which I derived from the protobuf definition from libpg_query.

https://gist.github.com/wesselvdv/c18d39550561bb5b76c7ebef1b82aac4

pgsql-parser uses parts of it, you can re-use the types to augment the module.

EDIT:

I've also updated it to be correct in terms of optional vs required. It's probably not entirely correct as I don't think my SQL files encompass the entirety of possibilities in terms of language.

It also contains the types for plpgsql parsing.

**Comment by jgoux** [comment]
Hello @wesselvdv, I'm very interested in the whole process for generating these types!

Could you describe which plugin did you use and if you had manual steps? I'd love to automate this (and run it against the last version of libpg-query).

**Comment by wesselvdv** [comment]
@jgoux no automated process unfortunately, just a very large set of postgresql files and the default regression test of postgres itself.

I am using [typia](https://github.com/samchon/typia)  to generate runtime checks for typescript definitions, and by letting it check the valid parsed output of libpg-query I can tweak the types to be conform what’s possible. I am however missing a lot of possibilities still.

I also checked the code of libpg-query itself, but for some cases they don’t even narrow it there.


The closest thing I found to a corpus of postgresql scripts was this repo: https://github.com/SKalt/sql_parser_tests

**Comment by jgoux** [comment]
@wesselvdv Wow ok I see, that's a huge work! 👏

I'm not familiar with protobuf, but is it not possible to convert this file https://github.com/pganalyze/libpg_query/blob/15-latest/protobuf/pg_query.proto to TypeScript with something like https://github.com/stephenh/ts-proto or https://github.com/improbable-eng/ts-protoc-gen ?

Won't it generate some kind of types?

**Comment by wesselvdv** [comment]
> @wesselvdv Wow ok I see, that's a huge work! 👏
> 
> I'm not familiar with protobuf, but is it not possible to convert this file https://github.com/pganalyze/libpg_query/blob/15-latest/protobuf/pg_query.proto to TypeScript with something like https://github.com/stephenh/ts-proto or https://github.com/improbable-eng/ts-protoc-gen ?
> 
> Won't it generate some kind of types?

Yes, with the emphasis on "some kind of". Here's a nice example of a message that has 3 properties (`objname`, `objargs` and `objfuncargs`) which have the type `repeated Node`:

```proto
message ObjectWithArgs
{
  repeated Node objname = 1 [json_name="objname"];
  repeated Node objargs = 2 [json_name="objargs"];
  repeated Node objfuncargs = 3 [json_name="objfuncargs"];
  bool args_unspecified = 4 [json_name="args_unspecified"];
}
```

If directly translated to typescript it'd be something like this:

```typescript
interface Node {
    Alias?: Alias;
    RangeVar?: RangeVar;
    TableFunc?: TableFunc;
    Expr?: Expr;
    Var?: Var;
    Param?: Param;
    Aggref?: Aggref;
    GroupingFunc?: GroupingFunc;
    WindowFunc?: WindowFunc;
    SubscriptingRef?: SubscriptingRef;
    FuncExpr?: FuncExpr;
    NamedArgExpr?: NamedArgExpr;
// ... snip another 150 types, but you get the gist
    CallContext?: CallContext;
    Integer?: PgInteger;
    Float?: PgFloat;
    String?: PgString;
    BitString?: PgBitString;
    Null?: PgNull;
    List?: PgList;
    IntList?: IntList;
    OidList?: OidList;
  }

  interface ObjectWithArgs {
    objname: Array<Node>;
    objargs?: Array<Node>;
    objfuncargs?: Array<Node>;
    args_unspecified?: boolean;
  }
```

What you can see from the directly translated example is that is pretending as if it's possible to have a `WindowFunc` or a `SelectStmt` node inside of the Array in `ObjectWithArgs.objname`. Which in truth is not possible. I've found out the actual set of possible values is much much much smaller for this example:

```typescript
// more reference interfaces OneOfTypeName, OneOfFunctionParameter, etc..

  interface PgString {
    sval: string;
  }

  interface OneOfString {
    String: PgString;
  }

  interface ObjectWithArgs {
    objname: Array<OneOfString>;
    objargs?: Array<OneOfTypeName | EmptyObject>;
    objfuncargs?: Array<OneOfFunctionParameter>;
    args_unspecified?: boolean;
  }
```

Now, this might be irrelevant for many use cases, and in which case you can just use the auto generated one. In my use case, this stuff caused an exponential increase in file size when trying to use typia to validate if a structure is of a specific type. (e.g. 1gb+ .js file vs 100Kb).

**Comment by pyramation** [comment]
Hey all! I've been working on a parser to get this issue resolved:
https://github.com/launchql/pg-proto-parser

This should also help improve the overall library when it gets integrated 🙌🏻

@wesselvdv @jgoux @beeing @TobyMellor @delaneyj 

also — ping me `pyramation` on telegram if you want to join a working group for all this to keep more in sync :)

**Comment by pyramation** [comment]
closed!

you can see the deparser types here:
https://github.com/launchql/pgsql-parser/blob/main/packages/deparser/types/deparser.d.ts

also, published a few more libraries for helpers:

* [@pgsql/enums](https://github.com/launchql/pgsql-parser/tree/main/packages/enums): Provides PostgreSQL AST enums in TypeScript, enhancing type safety and usability in projects interacting with PostgreSQL AST nodes.
* [@pgsql/types](https://github.com/launchql/pgsql-parser/tree/main/packages/types): Offers TypeScript type definitions for PostgreSQL AST nodes, facilitating type-safe construction, analysis, and manipulation of ASTs.
* [@pgsql/utils](https://github.com/launchql/pgsql-parser/tree/main/packages/utils): A utility library for working with PostgreSQL AST node enumerations in a type-safe way, easing enum name and value conversions.

Happy to make more utilities! Just getting started with leveraging the new proto parser :) 

@wesselvdv @jgoux @beeing @TobyMellor @delaneyj @darora
