### ISSUE TITLE
What version of libpg_query does this use?

### ISSUE THREAD

**Issue by rattrayalex** [constructive-io/pgsql-parser#29]
It's not clear from the README or package.json what version of https://github.com/pganalyze/libpg_query this uses. Could that be documented?

**Comment by pyramation** [comment]
built with `13-latest` libpg_query. From now we'll be using major versions to reflect the PG version.

Added docs to main readme, thanks for the note!

**Comment by rattrayalex** [comment]
Awesome thanks!
