### ISSUE TITLE
Missing AltSeqStmt 

### ISSUE THREAD

**Issue by WoLfulus** [constructive-io/pgsql-parser#32]
ALTER SCHEMA deparse isn't implemented.

**Comment by pyramation** [comment]
Thanks @WoLfulus :) do you have a few example statements that I can include in our tests?

**Comment by pyramation** [comment]
Should be fixed. Let me know if there are specific statements that are causing issues, cheers!

```
Successfully published:
 - pgsql-deparser@13.1.6
 - pgsql-parser@13.1.6
```

**Comment by WoLfulus** [comment]
Wow! Thank you so much!

I was planning on submitting a PR over the weekend. I wasn't expecting a fast response!

Thanks!
