### ISSUE TITLE
deparser doesn't support alter sequence queries

### ISSUE THREAD

**Issue by divyenduz** [constructive-io/pgsql-parser#41]
I am not sure if this is an issue in this repo or https://github.com/pganalyze/libpg_query. I know that `libpg_query` ports the original PG parser but have rolled their own deparse out and this repo seems to be using its own deparser? https://github.com/pyramation/pgsql-parser/blob/master/packages/deparser/src/deparser.js

Please let me know if this is something known or if there is a workaround. 

To reproduce: 

```
const { parse, deparse } = require('pgsql-parser');
const stmts = parse('ALTER SEQUENCE public."User_id_seq" OWNED BY public."User".id;');
console.log(stmts)
deparse(stmts[0])
```

Running this outputs

```
[ { RawStmt: { stmt: [Object], stmt_len: 61 } } ]
/Users/triage/zoid-415/node_modules/pgsql-deparser/main/deparser.js:270
        throw new Error(type + ' is not implemented: ' + JSON.stringify(node));
        ^

Error: AlterSeqStmt is not implemented: {"sequence":{"schemaname":"public","relname":"User_id_seq","inh":true,"relpersistence":"p","location":15},"options":[{"DefElem":{"defname":"owned_by","arg":[{"String":{"str":"public"}},{"String":{"str":"User"}},{"String":{"str":"id"}}],"defaction":"DEFELEM_UNSPEC","location":36}}]}
```

**Comment by pyramation** [comment]
thank you for the reproduction step! I'll take a look at this asap!

**Comment by pyramation** [comment]
@divyenduz should be fixed in 
```
Successfully published:
 - pgsql-deparser@13.1.9
 - pgsql-parser@13.1.9
```

let me know if there are other statements I'm missing! I tried to include a few alter statements in the fixtures

**Comment by divyenduz** [comment]
That was quick, thank you 🙌🏼
