### ISSUE TITLE
pgsql-parser browser version

### ISSUE THREAD

**Issue by silverbrancher** [constructive-io/pgsql-parser#59]
I was trying to use the library in browser.
So i used webpack and browserify library but failed both.

https://github.com/luckyfanghe/pgsql-parser/tree/webpack

How can i fix it?

**Comment by pyramation** [comment]
this requires a C library, so would not be usable in the browser! Sorry about that!

However, if you want the deparser, that is something that should be bundle-able. Do you need both the parser and deparser?

**Comment by beeing** [comment]
One interesting point is that with wasm, it's possible. And a quick search revealed a new project in https://github.com/xdatadocs/libpg_query-wasm/tree/wasm-exceptions
