### ISSUE TITLE
Loosen dependency on dotty

### ISSUE THREAD

**Issue by benasher44** [constructive-io/pgsql-parser#60]
Hi! Currently dotty is pinned to `0.1.0` in deparser. It would be great to loosen this to something like ~0.1.0 to allow patch version updates for recent security patches. Thanks!

**Comment by pyramation** [comment]
sure thing! I've updated in latest to use a caret, does that work for you?

https://github.com/pyramation/pgsql-parser/commit/e051201a163f5c3649d5ed0fbdcb170a78e85269

**Comment by benasher44** [comment]
Caret is great thanks!
