### ISSUE TITLE
Error: LockStmt is not implemented

### ISSUE THREAD

**Issue by acarl005** [constructive-io/pgsql-parser#68]
Explicit [`LOCK` statements](https://www.postgresql.org/docs/9.4/sql-lock.html) (type `LockStmt` in the parser) on tables are unimplemented, e.g. `LOCK TABLE "table_name" IN ACCESS EXCLUSIVE MODE`.

Happy to submit a PR if y'all are willing to support this. Please let me know.

**Comment by pyramation** [comment]
totally! please make a PR, that'd be great :)

**Comment by acarl005** [comment]
PR opened #75

**Comment by pyramation** [comment]
Thank you @acarl005  — fyi I had to make a few tweaks to allow tests to pass to support the final statement in the fixture, for `ONLY` to work https://github.com/pyramation/pgsql-parser/blob/master/packages/deparser/src/deparser.js#L1827-L1829

```
Successfully published:
 - pgsql-deparser@13.3.11
 - pgsql-parser@13.3.11
```

**Comment by pyramation** [comment]
if you're curious @acarl005 https://github.com/pyramation/pgsql-parser/blob/master/packages/deparser/src/deparser.js#L1827-L1829
