### ISSUE TITLE
COPY statement with deparse not supported?

### ISSUE THREAD

**Issue by dforsber** [constructive-io/pgsql-parser#72]
Thank you for creating this module! I just noticed that COPY statement is not supported for deparser, whilst the parser supports it.

**Comment by pyramation** [comment]
`COPY` is not sql, it is a part of `psql` command line if I'm not mistaken? Can you show an example?

**Comment by dforsber** [comment]
> `COPY` is not sql, it is a part of `psql` command line if I'm not mistaken? Can you show an example?

Yes, I'm using DuckDB and it is using modified psql parser. An example would be:

```sql
COPY (SELECT 1) TO 'test.csv' WITH (FORMAT 'CSV');
```

**Comment by dforsber** [comment]
@pyramation Thank you very much! 👍🏻
