### ISSUE TITLE
supabase artifact not found

### ISSUE THREAD

**Issue by patiee** [constructive-io/pgsql-parser#78]
```
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v13.2.5-node-v108-darwin-arm64.tar.gz
```

**Comment by darora** [comment]
@patiee it should fall back to building from source-is that not happening?

**Comment by maschwenk** [comment]
@darora / @pyramation is the prebuilding setup automatically or was it only setup for that one version?

**Comment by pyramation** [comment]
seems that it was failing to attempt the building from source step. I will try and confirm with @patiee offline to see, it could also be that the machine was an M1 and I know there may be some M1 issues still.

**Comment by patiee** [comment]
thank you @pyramation for fixing it, works perfectly :)

**Comment by krish40786** [comment]
@patiee @pyramation What was the solution to this?

**Comment by darora** [comment]
@krish40786 if you're just getting the warning mentioned in the original message, you should be able to move past that without error and it should get compiled from source.

If the compilation from source is failing, please open a new issue on this repo and we can take a look.
