### ISSUE TITLE
Question: why not async?

### ISSUE THREAD

**Issue by acarl005** [constructive-io/pgsql-parser#85]
Hi @pyramation, I have a question. I notice that the underlying `libpg-query` exposes both a sync and async entrypoint, `parseQuerySync` and `parseQuery`. However, `pgsql-parser` wraps the sync version but does not expose an async counterpart. Why is that? Is it for simplicity? Does the async version have no performance benefit?

**Comment by pyramation** [comment]
It just hasn't come up before. Do you want to expose it? Feel free to make a PR, I don't believe it changes the bundle size.

**Comment by acarl005** [comment]
Implemented in #86
