### ISSUE TITLE
New release of pgsql-parser for macOS SDK Issue

### ISSUE THREAD

**Issue by benasher44** [constructive-io/pgsql-parser#88]
Hi there! We're running into the same issue filed in  pyramation/libpg-query-node#23, but we're using it via pgsql-parser.

**Comment by pyramation** [comment]
please try out 

```
- pgsql-parser@13.4.0
```

NOTE:  we'll likely want to publish to the CDN @darora

**Comment by pyramation** [comment]
let me know if that works @benasher44

**Comment by benasher44** [comment]
Works now thanks!
